### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by MidnightTale** [CampHQmc/ServerChatHeads#5]
When start pre-gen world and then join server is crash

Log [https://cdn.hynse.net/public/logs/mc-crash-2024-02-06_12_52_15-server.txt](https://cdn.hynse.net/public/logs/mc-crash-2024-02-06_12_52_15-server.txt)

Edit: after restart server skin not load
![image](https://github.com/CampHQmc/ServerChatHeads/assets/125941391/c6aa0b65-5e53-40af-b323-3ab6c9620405)
```[13:07:35] [Server thread/INFO] (class_3324) xEglyvihbs[/10.154.1.200:6070] logged in with entity id 25 at (41.5, 73.0, 24.5)
[13:07:35] [Server thread/INFO] (owo) Sending server config values to client
[13:07:35] [Server thread/INFO] (class_2983) [STDOUT]: Ce : player joined, pausing chunky
[13:07:35] [Server thread/INFO] (MinecraftServer) [Chunky] Task paused for minecraft:overworld.
[13:07:35] [Server thread/INFO] (arte) Applying pack to player xEglyvihbs
[13:07:35] [Server thread/INFO] (voicechat) [voicechat] Using Fabric Permissions API
[13:07:35] [Thread-36/WARN] (class_3324) Failed to get image for xEglyvihbs
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]: javax.imageio.IIOException: Can't get input stream from URL!
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1407)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at net.minecraft.class_3324.chatheads$getPlayerHead(class_3324.java:7038)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at net.minecraft.class_3324.md1a17a6$chatheads$lambda$chatheads$invokeDownloadOnJoin$0$1(class_3324.java:7020)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at net.minecraft.class_3324.md1a17a6$chatheads$lambda$chatheads$invokeDownloadOnJoin$1$0(class_3324.java:7020)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/java.lang.Thread.run(Thread.java:1583)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]: Caused by: java.net.SocketException: Connection reset
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:318)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:346)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:796)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/java.net.Socket$SocketInputStream.read(Socket.java:1099)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:827)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:759)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:786)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1690)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1599)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.base/java.net.URL.openStream(URL.java:1325)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1405)
[13:07:35] [Thread-36/INFO] (class_2983) [STDERR]:      ... 5 more
[13:07:35] [Server thread/INFO] (MinecraftServer)    xEglyvihbs joined the game
[13:07:35] [Chunky-minecraft:overworld Thread/INFO] (MinecraftServer) [Chunky] Task stopped for minecraft:overworld.
[13:07:35] [Server thread/INFO] (class_3324) Async chunk loading for player xEglyvihbs completed
[13:07:36] [Server thread/WARN] (class_3244) Ignoring chat session from xEglyvihbs due to missing Services public key
[13:07:40] [Server thread/WARN] (MinecraftServer) Can't keep up! Is the server overloaded? Running 3082ms or 61 ticks behind
[13:07:48] [Server thread/INFO] (MinecraftServer)    xEglyvihbs: .
[13:07:51] [Server thread/INFO] (MinecraftServer)    xEglyvihbs: a
[13:08:36] [Server thread/INFO] (class_3898) Changing watch distance to 13
[13:08:36] [Server thread/INFO] (class_3898) Changing watch distance to 13
[13:08:36] [Server thread/INFO] (class_3898) Changing watch distance to 13```

**Comment by CamperSamu** [comment]
This looks like a server misconfiguration, I added some additional checks in the 1.20.5 update that will likely be backported once I get around to setup my projects with Forgix.
Closing for now
